apiVersion: apps/v1
kind: Deployment
metadata:
  name: filegator-app
  namespace: filegator
spec:
  selector:
    matchLabels:
      app: filegator
  template:
    metadata:
      labels:
        app: filegator
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: filegator-pvc
      - name: filegatorconfig
        configMap:
          name: filegator-conf
          items:
            - key: configuration.php
              path: configuration.php
      containers:
        - name: filegator
          image: filegator/filegator
          resources:
            requests:
              memory: "1024Mi"
              cpu: "500m"
          volumeMounts:
          - name: data
            mountPath: /var/www/filegator/repository
          - name: filegatorconfig
            mountPath: /var/www/filegator/configuration.php
            subPath: configuration.php
            readOnly: true